apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strimzi
helmCharts:
- includeCRDs: true
  name: strimzi-kafka-operator
  namespace: strimzi
  releaseName: strimzi
  repo: https://strimzi.io/charts/
  valuesInline:
    resources:
      limits:
        cpu: 0.5
        memory: 2Gi
      requests:
        cpu: 0.1
        memory: 512Mi
    watchAnyNamespace: true
  version: 0.38.0
