apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["postgres.acid-minimal-cluster.credentials.postgresql.acid.zalan.do"]
  verbs: ["get"]
