apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: iceberg-changes-sink
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.tabular.iceberg.connect.IcebergSinkConnector
  config:
    iceberg.catalog.client.region: us-west-1
    iceberg.control.commit.interval-ms: 30000
    iceberg.catalog.io-impl: org.apache.iceberg.aws.s3.S3FileIO
    iceberg.catalog.s3.access-key-id: minio
    iceberg.catalog.s3.endpoint: http://minio.minio.svc.cluster.local:80
    iceberg.catalog.s3.path-style-access: true
    iceberg.catalog.s3.secret-access-key: minio123
    iceberg.catalog.type: hive
    iceberg.catalog.uri: thrift://hive-metastore.hive:9083
    iceberg.catalog.warehouse: s3a://datalake/warehouse
    iceberg.tables.auto-create-enabled: true
    iceberg.tables.dynamic-enabled: true
    iceberg.tables.evolve-schema-enabled: true
    iceberg.tables.route-field: _cdc.target
    topics.regex: foo.public.*
    transforms: dbz
    transforms.dbz.cdc.target.pattern: default.{table}_changes
    transforms.dbz.type: io.tabular.iceberg.connect.transforms.DebeziumTransform
