apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spark-operator
helmCharts:
- includeCRDs: true
  name: spark-operator
  namespace: spark-operator
  releaseName: spark-operator
  repo: https://googlecloudplatform.github.io/spark-on-k8s-operator
  valuesInline:
    sparkJobNamespace: spark
    webhook:
      enable: true
      namespaceSelector: kubernetes.io/metadata.name=spark
  version: 1.1.27
