apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telepresence
helmCharts:
- name: telepresence
  namespace: telepresence
  releaseName: traffic-manager
  repo: https://app.getambassador.io
  version: 2.17.0
